// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpqruxpknjyznrcxqdxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcXJ1eHBrbmp5em5yY3hxZHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTczNzEsImV4cCI6MjA2OTQ5MzM3MX0.gMCa-yEIq9G5biAguBJAT0zs6PTPYECxlhBTaaMCopw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});